const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/Telur.jpg",
      name: "Telur Ayam",
      price: 15000,
      info: "Tersedia",
      stok: 1000,
      category: "Bahan Baku",
    },
    {
      id: 8,
      cover: "./images/shops/Milku.jpg",
      name: "Milku",
      price: 3000,
      info: "Tersedia",
      stok: 50,
      category: "Minuman",
    },
    {
      id: 9,
      cover: "./images/shops/Mie_Sarimi.jpg",
      name: "Mie Sarimi",
      price: 5000,
      info: "Tersedia",
      stok: 500,
      category: "Makanan",
    },
    {
      id: 10,
      cover: "./images/shops/Beras.jpg",
      name: "Beras",
      price: 348500,
      info: "Tersedia",
      stok: 30,
      category:"Bahan Baku",
    },
    {
      id: 11,
      cover: "./images/shops/GulaPasir_Bintang.jpg",
      name: "Gula Pasir Bintang",
      price: 17000,
      info: "Tersedia",
      stok: 20,
      category: "Bahan Baku",
    },
    {
      id: 12,
      cover: "./images/shops/Kopi_kapalApi.jpg",
      name: "Kopi Kapal Api",
      price: 11500,
      info: "Tersedia",
      stok: 100,
      Category: "Bahan Baku",
    },
    {
      id: 13,
      cover: "./images/shops/GulaPasir.jpg",
      name: "Gula Pasir ",
      price: 9500,
      info: "Tersedia",
      stok: 30,
      category: "Bahan Baku",
    },
    {
      id: 14,
      cover: "./images/shops/baby_potty.jpg",
      name: "Baby Potty Toilet ",
      price: 38000,
      info: "Kosong",
      stok: 0,
      category: "Barang Unik",
    },
    {
      id: 15,
      cover: "./images/shops/lipstik.jpg",
      name: "Metta Lip Gloss",
      price: 80000,
      info: "Tersedia",
      stok: 3,
      category: "Kosmetik"
    },
    {
      id: 16,
      cover: "./images/shops/Piring_palstik.jpg",
      name: "Piring Plastik",
      price: 15000,
      info: "Tersedia",
      stok: 40,
      category: "Barang Unik"
    },
  ],
}
export default Sdata
